<a href="https://colab.research.google.com/github/Mobodot/Ineuron_DL_assignments/blob/main/Alexnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment:
Modify the Alexnet architecture & train on the flower dataset shown in the session & try to acquire better accuracy that we got in the session using 5 epochs.



*** Class model Metrics:***
* loss: 3.6055
* acc: 0.3322
* val_loss: 587.08
* val_acc: 0.1140

*** New model Metrics: ***
* loss: 2.0150
* acc: 0.3401
* val_loss: 1.7096
* val_acc: 0.3750

*** Model Evaluation ***
* accuracy: 0.42867646
* loss: 1.5700099692625158


**NB:** The current model gotten can be said to stable model. As we can see that both train acc, val acc, and eval accuracy are so much on the same scale. It's possible to get a better/higher accuracy, but given that the condition was to improve the accuracy with only 5epochs, we can say this is a decent model.

In [3]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import (Dense, 
                          Flatten, 
                          Conv2D, 
                          MaxPooling2D,
                          BatchNormalization)


In [4]:
!pip install tflearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 107 kB 29.2 MB/s 
  Created wheel for tflearn: filename=tflearn-0.5.0-py3-none-any.whl size=127299 sha256=82ac747625f73ace8336e0ce1c62139a3131bc670695adf1afb6c934a6016f41
  Stored in directory: /root/.cache/pip/wheels/5f/14/2e/1d8e28cc47a5a931a2fb82438c9e37ef9246cc6a3774520271
Successfully built tflearn


In [5]:
import tflearn.datasets.oxflower17 as oxflower17
x, y = oxflower17.load_data(one_hot=True)

Instructions for updating:
non-resource variables are not supported in the long term


100.0% 60276736 / 60270631


Succesfully downloaded 17flowers.tgz 60270631 bytes.
File Extracted
Starting to parse images...
Parsing Done!


In [6]:
x[0]

array([[[0.10980392, 0.16470589, 0.0627451 ],
        [0.10980392, 0.16470589, 0.06666667],
        [0.11372549, 0.16078432, 0.07058824],
        ...,
        [0.14117648, 0.21176471, 0.08235294],
        [0.13725491, 0.19607843, 0.07450981],
        [0.13725491, 0.1882353 , 0.07843138]],

       [[0.10980392, 0.16470589, 0.0627451 ],
        [0.10980392, 0.16078432, 0.0627451 ],
        [0.10980392, 0.15686275, 0.06666667],
        ...,
        [0.13725491, 0.20784314, 0.08235294],
        [0.13333334, 0.19607843, 0.07450981],
        [0.13333334, 0.18431373, 0.07450981]],

       [[0.10980392, 0.16470589, 0.0627451 ],
        [0.10588235, 0.16078432, 0.0627451 ],
        [0.10196079, 0.14901961, 0.05882353],
        ...,
        [0.13333334, 0.20392157, 0.07843138],
        [0.12941177, 0.19215687, 0.07058824],
        [0.12941177, 0.18039216, 0.07058824]],

       ...,

       [[0.3647059 , 0.5058824 , 0.15686275],
        [0.34509805, 0.4745098 , 0.16470589],
        [0.28235295, 0

In [7]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
x.shape

(1360, 224, 224, 3)

In [9]:
y.shape

(1360, 17)

In [84]:
model = Sequential()

# 1st conv layer
model.add(Conv2D(filters=96, 
                 kernel_size=(11,11), 
                 strides=(4,4),
                 padding="valid", 
                 activation="relu",
                 input_shape=(224,224,3)))
# pooling
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding="valid"))

# Batch Normalization before passing it ot the next layer
model.add(tf.keras.layers.BatchNormalization())

# 2nd conv layer
model.add(Conv2D(filters=256, 
                 kernel_size=(5,5), 
                 strides=(1,1), 
                 activation="relu",
                 padding="same"))
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding="valid"))
model.add(tf.keras.layers.BatchNormalization())

# 3rd conv layer
model.add(Conv2D(filters=356, 
                 kernel_size=(3,3), 
                 strides=(1,1),
                 activation="relu",
                 padding="valid",))
model.add(tf.keras.layers.BatchNormalization())

# 4th conv layer
model.add(Conv2D(filters=300, 
                 kernel_size=(3,3), 
                 strides=(1,1),
                 activation="relu",
                 padding="valid",))
model.add(tf.keras.layers.BatchNormalization())

# 5th conv layer
model.add(Conv2D(filters=128, 
                 kernel_size=(3,3), 
                 strides=(1,1),
                 activation="relu",
                 padding="valid",))
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding="valid"))
model.add(tf.keras.layers.BatchNormalization())


model.add(Flatten())

# 1st dense layer
model.add(Dense(4096, activation="relu"))
# model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.BatchNormalization())


# 2nd dense layer
model.add(Dense(4000, activation="relu"))
# model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.BatchNormalization())

# 3rd dense layer
model.add(Dense(17, activation="softmax"))

model.summary()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_95 (Conv2D)          (None, 54, 54, 96)        34944     
                                                                 
 max_pooling2d_57 (MaxPoolin  (None, 26, 26, 96)       0         
 g2D)                                                            
                                                                 
 batch_normalization_133 (Ba  (None, 26, 26, 96)       384       
 tchNormalization)                                               
                                                                 
 conv2d_96 (Conv2D)          (None, 26, 26, 256)       614656    
                                                                 
 max_pooling2d_58 (MaxPoolin  (None, 12, 12, 256)      0         
 g2D)                                                            
                                                     

In [85]:
model.compile(loss=keras.metrics.categorical_crossentropy, 
              optimizer=keras.optimizers.Adam(learning_rate=0.01),
              metrics=["accuracy"])

In [86]:
# training
model.fit(x,y, batch_size=8, 
          epochs=5, 
          verbose=1,
          validation_split=.2,
          shuffle=True)

Train on 1088 samples, validate on 272 samples
Epoch 1/5
1088/1088 [==============================] - 5s 4ms/sample - loss: 19.3765 - acc: 0.1535 - val_loss: 48.1579 - val_acc: 0.1324
Epoch 2/5
1088/1088 [==============================] - 3s 3ms/sample - loss: 6.7415 - acc: 0.1765 - val_loss: 14.9370 - val_acc: 0.2243
Epoch 3/5
1088/1088 [==============================] - 3s 3ms/sample - loss: 3.5634 - acc: 0.2408 - val_loss: 2.2668 - val_acc: 0.2794
Epoch 4/5
1088/1088 [==============================] - 3s 3ms/sample - loss: 2.3084 - acc: 0.3079 - val_loss: 1.9520 - val_acc: 0.3676
Epoch 5/5
1088/1088 [==============================] - 3s 3ms/sample - loss: 2.0150 - acc: 0.3401 - val_loss: 1.7096 - val_acc: 0.3750


In [87]:
model.evaluate(x, y)

[1.5700099692625158, 0.42867646]

In [88]:
x_pred = x[0:3]


array([[[[0.10980392, 0.16470589, 0.0627451 ],
         [0.10980392, 0.16470589, 0.06666667],
         [0.11372549, 0.16078432, 0.07058824],
         ...,
         [0.14117648, 0.21176471, 0.08235294],
         [0.13725491, 0.19607843, 0.07450981],
         [0.13725491, 0.1882353 , 0.07843138]],

        [[0.10980392, 0.16470589, 0.0627451 ],
         [0.10980392, 0.16078432, 0.0627451 ],
         [0.10980392, 0.15686275, 0.06666667],
         ...,
         [0.13725491, 0.20784314, 0.08235294],
         [0.13333334, 0.19607843, 0.07450981],
         [0.13333334, 0.18431373, 0.07450981]],

        [[0.10980392, 0.16470589, 0.0627451 ],
         [0.10588235, 0.16078432, 0.0627451 ],
         [0.10196079, 0.14901961, 0.05882353],
         ...,
         [0.13333334, 0.20392157, 0.07843138],
         [0.12941177, 0.19215687, 0.07058824],
         [0.12941177, 0.18039216, 0.07058824]],

        ...,

        [[0.3647059 , 0.5058824 , 0.15686275],
         [0.34509805, 0.4745098 , 0.16470589]

## Predictions

In [102]:
x[:2].shape

(2, 224, 224, 3)

In [118]:
y_pred = model.predict(x[:10])
y_actual = y[:10]

In [119]:
import numpy as np

print(f"predictions: --> {np.argmax(y_pred, axis=1)}")
print("*"*20)
print(f"Actual: --> {np.argmax(y_actual, axis=1)}")

predictions: --> [ 2 14 10  0 14  8  0  2  6 10]
********************
Actual: --> [ 7 13  8  5  5  8 12  2  4 10]
